workflows:
  flutter_with_python:
    name: Flutter + Chaquopy (spaCy offline)
    environment:
      flutter: stable
    scripts:
      - name: Setup Python dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk